language: node_js
node_js: 
  - "6.10.1"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

after_success:
  notifications:
    email:
      - francaniilista@gmail.com
  
after_failure:
  notifications:
    email:
      - francaniilista@gmail.com