language: node_js
node_js: 
  - "6.10.1"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - sleep 3
  - 'npm install grunt'
  - 'npm install grunt-cli'
  - 'npm install grunt-protractor-webdriver'
  - 'npm install grunt-protractor-runner'
  - 'npm install protractor'
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install
script:
  - 'node_modules/protractor/bin/webdriver-manager update --standalone --chrome'
  - 'node_modules/protractor/bin/webdriver-manager start 2>&1 &'
  - npm run test


notifications:
  email:
    recipients:
      - francaniilista@gmail.com
    on_success: always